Sprint 6 solution
f-berezyuk/java-kanban pull request #2
Opened 2024-05-03 21:04 UTC by f-berezyuk

Финальный проект 6 спринта.
Теперь historyManager может хранить сколько угодно записей о тасках. Но только в единственном экземпляре (одна запись для одной таски). Так же, при удалении таски - удаляется и её история.

Выполнил экстра задачу. Единственное, не стал делать это в main, а сделал в классе тестов, так как там есть удобные инструменты для создания тасок.

2024-05-05 22:19 UTC, mikita95 requested changes
Все отлично :) Оставил лишь небольшие замечания

2024-05-05 22:19 UTC, mikita95 commented on src/tracker/MySimpleLinkedHashMap.java
> +    Node head;
Не хватает модификатора доступа, сейчас поле доступно всем в пакете :)

2024-05-06 17:13 UTC, f-berezyuk commented on src/tracker/MySimpleLinkedHashMap.java
> +    Node head;
Исправил)

2024-05-07 11:23 UTC, irek-valiev approved these changes

2024-05-07 13:00 UTC, merged