sprint_7: Add file based manager. Add tests. Add some extra methods. …
f-berezyuk/java-kanban pull request #3
Opened 2024-05-17 22:57 UTC by f-berezyuk

Complete sprint 7 task.

2024-05-18 22:40 UTC, mikita95 requested changes
Все сделано отлично :) Оставил лишь небольшие замечания

2024-05-18 22:40 UTC, mikita95 commented on src/task/EpicTask.java
> +    public EpicTask(Task clone) {
Можно просто принимать EpicTask здесь, чтобы не использовать instanceof

2024-05-18 22:40 UTC, mikita95 commented on src/task/Task.java
> +        return String.join(delimiter, id.toString(), type.toString(), name, status.toString(), description);
Сейчас вы подстроили реализацию метода toString под конкретную реализацию другой логики, хотя модель данных вообще ничего не знает про csv. Лучше для преобразования задач в формат csv сделать отдельный утилитный класс

2024-05-18 22:40 UTC, mikita95 commented on src/tracker/InMemoryTaskManager.java
> +    public Task fromString(String value) throws NumberFormatException {
Лучше перенести эти методы в утилитный класс для работы именно с csv файлами, тут им не место

2024-05-18 22:40 UTC, mikita95 commented on src/tracker/FileBackedTaskManager.java
> +            }
Нужно также восстановить счётчик id и историю :)

2024-05-20 19:26 UTC, f-berezyuk commented on src/tracker/FileBackedTaskManager.java
> +            }
Добавил логику, чтобы счётчик мог реагировать на добавление таска с проставленным ИД.
Как восстановить историю не представляю. Но так как история хранит все таски внутри себя в порядке их использования, то я решил, что проще сохранять историю в файл, и из него восстанавливать. Так будут таски, так будет и история)

Есть корнер-кейсы, если мы руками удалим из истории какие-либо записи о таске. Это можно решить, но кажется, это уже чрезмерное усложнение(

2024-05-20 21:42 UTC, f-berezyuk commented on src/task/Task.java
> +        return String.join(delimiter, id.toString(), type.toString(), name, status.toString(), description);
Сделал. Вынес в отдельный класс утилитарные методы, насколько это было возможно.

2024-05-20 21:48 UTC, f-berezyuk commented on src/task/EpicTask.java
> +    public EpicTask(Task clone) {
Нет, нельзя.
Сейчас, этот конструктор позволяет мне считывать данные из файла эффективнее:
я сразу создаю простой таск, как считал первую часть сообщения, после этого я могу проверить тип таски и с помощью неё создать необходимую мне таску, не переопределяя в каждом кейсе общие поля для всех тасок.

Если использовать тут epic task, то рефлексия уедет на уровень выше. А я хочу, чтобы у тасок был конструктор, позволяющий из одного типа таски получить другой тип таски. С этим конструктором я могу так сделать)

А если поставть epic task, то потребуется сделать ещё один конструктор, который бы принимал полный набор полей. Или в методе по выгрузке из файла дополнительно перепоределять Ид у новых тасок.

2024-05-20 21:48 UTC, f-berezyuk commented on src/tracker/InMemoryTaskManager.java
> +    public Task fromString(String value) throws NumberFormatException {
Сделал

2024-05-26 16:30 UTC, mikita95 approved these changes
Все отлично :) Можно мержить пул-реквест

2024-05-26 18:53 UTC, merged