sprint_9: Init
f-berezyuk/java-kanban pull request #5
Opened 2024-06-01 22:34 UTC by f-berezyuk

9 домашнее задание
Work in progress

2024-06-03 22:44 UTC, mikita95 requested changes
Все сделано отлично :) Оставил лишь небольшое замечание

2024-06-03 22:44 UTC, mikita95 commented on src/api/HttpTaskServer.java
> +            throw new RuntimeException(e);
Лучше завести кастомное исключение и бросать его, сейчас сложно будет разобрать ошибки

2024-06-03 23:31 UTC, f-berezyuk commented on src/api/HttpTaskServer.java
> +            throw new RuntimeException(e);
Тут же только исключения при создании сервера вылетают. А уже от хендлеров идут осмысленные ошибки (перехват исключений и последующие 4хх или 5хх)

2024-06-04 19:34 UTC, mikita95 approved these changes
Все отлично :) Можно мержить пул-реквест

2024-06-06 14:12 UTC, merged